<?xml version="1.0" ?>  
<!DOCTYPE bookstore[
<!ELEMENT bookstore (book+)>
<!ELEMENT book (title+,author,year,price)>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title lang CDATA "en" >
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]>
<?xml-stylesheet type="text/xsl" href="style.xsl" ?>
<bookstore>
  <book >
    <title lang="en">Everyday Italian</title>
    <author>Giada De Laurentiis</author>
    <year>2005</year>
    <price>30.00</price>
  </book>
  <book >
    <title lang="en">Everyday Italian</title>
    <author>Giada De Laurentiis</author>
    <year>2005</year>
    <price>20.00</price>
  </book>
  <book >
    <title lang="en">Everyday Italian</title>
    <author>Giada De Laurentiis</author>
    <year>2005</year>
    <price>90.00</price>
  </book>
  <book >
    <title lang="en">Everyday Italian</title>
    <author>Giada De Laurentiis</author>
    <year>2005</year>
    <price>10.00</price>
  </book>
</bookstore>